//
//  MemeWorker.swift
//  Clase 6
//
//  Created by Luis Padilla  on 3/2/19.
//  Copyright (c) 2019 Luis Padilla . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MemeWorker
{
    var store : MemeStoreProtocol
    
    init(store : MemeStoreProtocol) {
        self.store = store
    }
    
    func fetchMemes(searchCriteria : String, completionHandler : @escaping([Meme]?, ServiceError?) -> Void) {
        store.fetchMemes(searchCriteria: searchCriteria, completionHandler: completionHandler)
    }
}

protocol MemeStoreProtocol {
    func fetchMemes(searchCriteria : String, completionHandler : @escaping([Meme]?, ServiceError?) -> Void)
}
