target 'Clase 6' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher'
  pod 'Alamofire'
  # pod 'R.swift’, ‘5.0.0.alpha.1’
  pod 'JGProgressHUD'
  # Pods for Clase 6

end
